# Generated by Django 3.2.9 on 2021-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
